apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "kong"
bases:
- ../base/
resources:
- service.yaml
patches:
- path: deployment-patches.yaml
  target:
    version: v1
    kind: Deployment
    name: ingress-kong
- path: service-patches.yaml
  target:
    version: v1
    kind: Service
    name: kong-proxy