---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-to-httpbin
  annotations:
    konghq.com/plugins: basic-auth-plugin
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - backend:
          service:
            name: httpbin-service
            port:
              number: 80
        path: /basic
        pathType: Prefix
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: basic-auth-plugin
config: 
  hide_credentials: true
plugin: basic-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: basic-auth-user
  annotations:
    kubernetes.io/ingress.class: "kong"
username: basic-auth-username
credentials:
  - basic-auth-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
type: Opaque
stringData:
  kongCredType: basic-auth
  username: testuser
  password: testpass