---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-to-httpbin
  annotations:
    konghq.com/plugins: key-auth-plugin
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - backend:
          service:
            name: httpbin-service
            port:
              number: 80
        path: /keyauth
        pathType: Prefix
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth-plugin
config: 
  hide_credentials: false
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: key-auth-tester
  annotations:
    kubernetes.io/ingress.class: "kong"
username: key-auth-tester
credentials:
  - key-auth-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: key-auth-secret
type: Opaque
stringData:
  kongCredType: key-auth
  key: api-secret-key